#!/usr/bin/env python3
"""Generate a manifest for LM-MHD diagnostic artifacts.

The manifest records file hashes, byte sizes, CSV row counts, and PNG sanity
metadata. It is an audit helper for unattended runs, not a physics diagnostic.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
from pathlib import Path

from PIL import Image, ImageStat

ROOT = Path(__file__).resolve().parents[2]

PREFIXES = (
    "axisymmetric_feedback_probe_sensitivity",
    "axisymmetric_inductionless_toroidal_feedback",
    "axisymmetric_loop_voltage_feedback",
    "axisymmetric_loop_voltage_threshold",
    "coupling_snapshot_audit",
    "full_induction_low_rm_bridge",
    "lm_mhd_regime_priority",
    "plasma_interface_current_feedback_scan",
    "plasma_interface_free_surface_gate_scan",
    "plasma_interface_marangoni_scan",
    "plasma_interface_sheath_scan",
    "plasma_interface_thermal_response_scan",
    "reference_matrix",
)
SUFFIXES = (".csv", ".h5", ".md", ".png")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", default="cases/lm_mhd_coupling/results", help="results directory")
    return parser.parse_args()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def csv_rows(path: Path) -> int | str:
    try:
        with path.open(newline="") as handle:
            return max(0, sum(1 for _ in csv.reader(handle)) - 1)
    except csv.Error as exc:
        return f"csv-error:{exc}"


def png_metadata(path: Path) -> dict[str, str | float | int]:
    image = Image.open(path).convert("L")
    stat = ImageStat.Stat(image)
    return {
        "image_width": image.size[0],
        "image_height": image.size[1],
        "image_luma_stddev": float(stat.stddev[0]),
        "image_nonblank": str(image.getbbox() is not None).lower(),
    }


def manifest_rows(results: Path) -> list[dict[str, str | int | float]]:
    files = [
        path
        for path in sorted(results.iterdir())
        if path.is_file() and path.suffix in SUFFIXES and any(path.name.startswith(prefix) for prefix in PREFIXES)
    ]
    rows: list[dict[str, str | int | float]] = []
    for path in files:
        row: dict[str, str | int | float] = {
            "path": str(path.relative_to(ROOT)),
            "suffix": path.suffix,
            "bytes": path.stat().st_size,
            "sha256": sha256(path),
            "csv_rows": "",
            "image_width": "",
            "image_height": "",
            "image_luma_stddev": "",
            "image_nonblank": "",
        }
        if path.suffix == ".csv":
            row["csv_rows"] = csv_rows(path)
        if path.suffix == ".png":
            row.update(png_metadata(path))
        rows.append(row)
    return rows


def write_manifest(results: Path, rows: list[dict[str, str | int | float]]) -> None:
    path = results / "lm_mhd_artifact_manifest.csv"
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]), lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_summary(results: Path, rows: list[dict[str, str | int | float]]) -> None:
    png_rows = [row for row in rows if row["suffix"] == ".png"]
    csv_rows_list = [row for row in rows if row["suffix"] == ".csv"]
    h5_rows = [row for row in rows if row["suffix"] == ".h5"]
    md_rows = [row for row in rows if row["suffix"] == ".md"]
    nonblank = sum(row["image_nonblank"] == "true" for row in png_rows)
    lines = [
        "# LM-MHD artifact manifest",
        "",
        "This file is generated by `cases/lm_mhd_coupling/lm_mhd_artifact_manifest.py`.",
        "It records file hashes, CSV row counts, and PNG sanity metadata for the",
        "current LM-MHD diagnostic artifacts. It is an audit inventory, not a",
        "physics validation result.",
        "",
        "Summary:",
        f"- manifest entries = {len(rows)}",
        f"- CSV files = {len(csv_rows_list)}",
        f"- PNG files = {len(png_rows)} ({nonblank}/{len(png_rows)} nonblank)",
        f"- HDF5 files = {len(h5_rows)}",
        f"- Markdown summaries = {len(md_rows)}",
        "",
        "Generated files:",
        "- `lm_mhd_artifact_manifest.csv`",
        "- `lm_mhd_artifact_manifest_summary.md`",
        "",
        "Red-team interpretation:",
        "- A hash proves artifact identity, not physics correctness.",
        "- A nonblank PNG check catches empty render failures, not misleading",
        "  axes, units, or model assumptions.",
        "- CSV row counts are useful for detecting truncated scans.",
    ]
    (results / "lm_mhd_artifact_manifest_summary.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    args = parse_args()
    results = ROOT / args.results
    rows = manifest_rows(results)
    if not rows:
        raise RuntimeError(f"no manifest files found in {results}")
    write_manifest(results, rows)
    write_summary(results, rows)
    print(f"Wrote LM-MHD artifact manifest for {len(rows)} files to {results}")


if __name__ == "__main__":
    main()
